const USER_TYPES = {
    EMPLOYEE: "EMPLOYEE",
    EMPLOYEE_MANAGER: "EMPLOYEE_MANAGER",
    INVENTORY_MANAGER: "INVENTORY_MANAGER",
    SUPPLIER_MANAGER:"SUPPLIER_MANAGER",
    DELIVERY_MANAGER:"DELIVERY_MANAGER",
    TRANSPORT_MANAGER:"TRANSPORT_MANAGER",
    PRODUCT_MANAGER:"PRODUCT_MANAGER",
    PAYMENT_MANAGER:"PAYMENT_MANAGER",
    CUSTOMER:"CUSTOMER",
    CUSTOMER_MANAGER:"CUSTOMER_MANAGER",
    GUEST:"GUEST",
    
}

module.exports = {
    USER_TYPES
}